services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evetools_vue
    ports:
      - "8080:8080"
    networks:
      evetools:
        ipv4_address: 10.169.0.20

networks:
  evetools:
    external: true